#!/bin/bash

# when set to exit, mpd_control will exit if you press escape
# when set to break, mpd_control will go the upper level if possible
ESC_ACTION="break"
# source configuration file for rofi if exists

ROFI="rofi -dmenu -i -p Search"
PORT=6600

# check if mpc is in PATH

if [! -x "$(command -v foo)" ]; then 
	echo "ERROR: mpc is not installed"
	exit
fi

add_after_current_song(){
	
	# playlist is empty, just add the song
	if [ "$(mpc -p $PORT playlist | wc -l)" == "0" ]; then
		mpc -p $PORT add "$1" 

	# there is no current song so mpd is stopped
	# it seems to be impossible to determine the current songs' position when 
	# mpd is stopped, so just add to the end
	elif [ -z "$(mpc -p $PORT current)" ]; then 
		mpc -p $PORT play
		CUR_POS=$(mpc -p $PORT  | tail -2 | head -1 | awk '{print $2}' | sed 's/#//' | awk -F/ '{print $1}')
		END_POS=$(mpc -p $PORT playlist | wc -l)
		mpc -p $PORT add "$1"
		mpc -p $PORT move $(($END_POS+1)) $(($CUR_POS+1))	
		mpc -p $PORT stop

	# at least 1 song is in the playlist, determine the position of the 
	# currently played song and add $1 after it
	else

		CUR_POS=$(mpc -p $PORT  | tail -2 | head -1 | awk '{print $2}' | sed 's/#//' | awk -F/ '{print $1}')
		END_POS=$(mpc -p $PORT playlist | wc -l)
		mpc -p $PORT add "$1"
		mpc -p $PORT move $(($END_POS+1)) $(($CUR_POS+1))	
	fi
}
add_after_current_song_and_play(){

	#playlist is empty, just add the song
	if [ "$(mpc -p $PORT playlist | wc -l)" == "0" ]; then
		mpc -p $PORT add "$1" 
		mpc -p $PORT play

	#there is no current song so mpd is stopped
	#it seems to be impossible to determine the current songs' position when 
	#mpd is stopped, so just add to the end
	elif [ -z "$(mpc -p $PORT current)" ]; then 
		mpc -p $PORTplay
		CUR_POS=$(mpc -p $PORT  | tail -2 | head -1 | awk '{print $2}' | sed 's/#//' | awk -F/ '{print $1}')
		END_POS=$(mpc -p $PORT playlist | wc -l)
		mpc -p $PORT add "$1"
		mpc -p $PORT move $(($END_POS+1)) $(($CUR_POS+1))	
		mpc -p $PORT play $(($CUR_POS+1))

	#at least 1 song is in the playlist, determine the position of the 
	#currently played song and add $1 after it
	else

		CUR_POS=$(mpc -p $PORT | tail -2 | head -1 | awk '{print $2}' | sed 's/#//' | awk -F/ '{print $1}')
		END_POS=$(mpc -p $PORT playlist | wc -l)
		mpc -p $PORT add "$1"
		mpc -p $PORT move $(($END_POS+1)) $(($CUR_POS+1))	
		mpc -p $PORT play $(($CUR_POS+1))
	fi
}

search_by_artist () {

	while true; do

		ARTIST="$(mpc -p $PORT list artist | sort -f | $ROFI)";
		if [ "$ARTIST" = "" ]; then $ESC_ACTION; fi
		
		while true; do

			ALBUMS=$(mpc -p $PORT list album artist "$ARTIST" | sort -f);
			ALBUM=$(echo -e "replace all\nadd all\n--------------------------\n$ALBUMS" | $ROFI);
			if [ "$ALBUM" = "" ]; then $ESC_ACTION;
			
			elif [ "$ALBUM" = "replace all" ]; then
				CUR_SONG=$(mpc -p $PORT current)
				mpc -p $PORT clear
				mpc -p $PORT find artist "$ARTIST" | mpc -p $PORT add 
				if [ -n "$CUR_SONG" ]; then mpc -p $PORT  play; fi
				$ESC_ACTION
			elif [ "$ALBUM" = "add all" ]; then 
				mpc -p $PORT find artist "$ARTIST" | mpc -p $PORT add
				$ESC_ACTION
			fi
			
			while true; do
				
				TITLES=$(mpc -p $PORT list title artist "$ARTIST" album "$ALBUM")
				TITLE=$(echo -e "replace all\nadd all\n--------------------------\n$TITLES" | $ROFI);
				if [ "$TITLE" = "" ]; then $ESC_ACTION
				elif [ "$TITLE" = "replace all" ]; then
					CUR_SONG=$(mpc -p $PORT current)
					mpc -p $PORT clear;
					mpc -p $PORT find artist "$ARTIST" album "$ALBUM" | mpc -p $PORT add 
					if [ -n "$CUR_SONG" ]; then mpc -p $PORT play; fi
					$ESC_ACTION
				elif [ "$TITLE" = "add all" ]; then
					mpc -p $PORT find artist "$ARTIST" album "$ALBUM" | mpc -p $PORT add 
					$ESC_ACTION
				
				fi

				while true; do
					DEC=$(echo -e "add after current and play\nadd after current\nreplace\nadd at the end" | $ROFI);
					case $DEC in 

						"")
						$ESC_ACTION
						;;

						"add after current and play")
						add_after_current_song_and_play "$(mpc -p $PORT find artist "$ARTIST" album "$ALBUM" title "$TITLE" | head -1 )"
						;;

						"add after current")
						add_after_current_song "$(mpc -p $PORT find artist "$ARTIST" album "$ALBUM" title "$TITLE" | head -1 )"
						;;

						"replace")
						CUR_SONG=$(mpc -p $PORT current)
						mpc -p $PORT clear
						mpc -p $PORT find artist "$ARTIST" album "$ALBUM" title "$TITLE" | head -1 | mpc -p $PORT add
						if [ -n "$CUR_SONG" ]; then mpc -p $PORT play; fi
						;;
						
						"add at the end")
						mpc -p $PORT find artist "$ARTIST" album "$ALBUM" title "$TITLE" | head -1 | mpc -p $PORT add
						;;

					esac
					$ESC_ACTION
				done
			done
		done
	done
}

search_by_track () {

	TITLE=$(mpc -p $PORT list title | sort -f | $ROFI)
	if [ "$TITLE" = "" ]; then exit; fi
	
	SONG=$(mpc -p $PORT find title "$TITLE" | head -1) 
	add_after_current_song "$SONG"

}

search_by_track_play_now () {

	TITLE=$(mpc -p $PORT list title | sort -f | $ROFI)
	if [ "$TITLE" = "" ]; then exit; fi
	
	SONG=$(mpc -p $PORT find title "$TITLE" | head -1) 
	add_after_current_song_and_play "$SONG"

}

play_playlist () {

	AVAIL_PLAYLISTS=$(mpc -p $PORT lsplaylists)
	PLAYLIST=$(mpc -p $PORT lsplaylists | $ROFI);
	if [ "$PLAYLIST" = "" ]; then exit; fi
	# Check if answer is in available playlists; otherwise exit
	# Prevents non-existant playlist from being added
	for PL in $AVAIL_PLAYLISTS 
		do
		if [ "$PL" = "$PLAYLIST" ]; then
		CUR_SONG=$(mpc -p $PORT current)
		mpc -p $PORT clear
		mpc -p $PORT load "$PLAYLIST";
		if [ -n "$CUR_SONG" ]; then mpc -p $PORT play; fi
		fi
	done
	exit

}

jump_to_song () {

	TITLE=$(mpc -p $PORT playlist | $ROFI);
	if [ "$TITLE" = "" ]; then exit; fi
	POS=$(mpc -p $PORT playlist | grep -n "$TITLE" | awk -F: '{print $1}')
	mpc -p $PORT play $POS;

}

search_by_album () {

	while true; do

		ALBUM=$(mpc -p $PORT list album | sort -f | $ROFI);
		if [ "$ALBUM" = "" ]; then $ESC_ACTION;
		fi
		
		while true; do
			
			TITLES=$(mpc -p $PORT list title album "$ALBUM")
			TITLE=$(echo -e "replace all\nadd all\n--------------------------\n$TITLES" | $ROFI);
			if [ "$TITLE" = "" ]; then $ESC_ACTION
			elif [ "$TITLE" = "replace all" ]; then
				CUR_SONG=$(mpc -p $PORT current)
				mpc -p $PORT clear;
				mpc -p $PORT find album "$ALBUM" | mpc -p $PORT add 
				if [ -n "$CUR_SONG" ]; then mpc -p $PORT play; fi
				$ESC_ACTION
			elif [ "$TITLE" = "add all" ]; then
				mpc -p $PORT find album "$ALBUM" | mpc -p $PORT add 
				$ESC_ACTION
			
			fi

			while true; do
				DEC=$(echo -e "add after current and play\nadd after current\nreplace\nadd at the end" | $ROFI);
				case $DEC in 

					"")
					$ESC_ACTION
					;;

					"add after current and play")
					add_after_current_song_and_play "$(mpc -p $PORT find album "$ALBUM" title "$TITLE" | head -1 )"
					;;

					"add after current")
					add_after_current_song "$(mpc -p $PORT find album "$ALBUM" title "$TITLE" | head -1 )"
					;;

					"replace")
					CUR_SONG=$(mpc -p $PORT current)
					mpc -p $PORT clear
					mpc -p $PORT find album "$ALBUM" title "$TITLE" | head -1 | mpc -p $PORT add
					if [ -n "$CUR_SONG" ]; then mpc -p $PORT play; fi
					;;
					
					"add at the end")
					mpc -p $PORT find album "$ALBUM" title "$TITLE" | head -1 | mpc -p $PORT add
					;;

				esac
				$ESC_ACTION
			done
		done
	done

}

shuffle() {

	mpc -p $PORT shuffle

}

display_help () {

	echo "-a, --artist		search for artist, then album, then title"
    	echo "-t, --track		search for a single track in the whole database"
    	echo "-n, --now			search for a single track in the whole database and play it now"
	echo "-p, --playlist		search for a playlist load it"
	echo "-j, --jump		jump to another song in the current playlist"		 
	echo "-l, --longplayer		search for album, then title"
	echo "-s, --shuffle		shuffle songs"
	echo "--auto			choose option in rofi"

}
case $1 in
	
	-a|--artist)
		search_by_artist
	;;

	-t|--track)
		search_by_track
	;;

	-n|--now)	
		search_by_track_play_now
	;;

	-p|--playlist)
		play_playlist
	;;

	-j|--jump)
		jump_to_song	
	;;

	-l|--longplayer)
		search_by_album	
	;;

	-s|--shuffle)
		shuffle
	;;
	--auto)
		CHOICE=$(echo -e "By Artist\nBy Album\nBy Track\nBy Now\nJump\nShuffle"| $ROFI);
		if [ "$CHOICE" = "By Artist" ]; then search_by_artist; fi
		if [ "$CHOICE" = "By Album" ]; then search_by_album; fi
		if [ "$CHOICE" = "By Track" ]; then search_by_track; fi
		if [ "$CHOICE" = "By Now" ]; then search_by_track_play_now; fi
		if [ "$CHOICE" = "Jump" ]; then jump_to_song; fi
		if [ "$CHOICE" = "Shuffle" ]; then shuffle; fi
		exit
	;;

	-h|--help)
		display_help
	;;
	
	*)
	echo "Usage: rofi-mpd [OPTION]"
	echo "Try 'rofi-mpd --help' for more information."
	;;

esac

